firegento/firegento-magesetup2

composer.json
please don't require fixed versions since this is not installable anymore with magento2 release (or any other version then 1.0.0-beta)
=> remove fixed versions

view/frontend/layout/catalog_category_view.xml
This PR fixes issue ##52
<update handle/> was placed in body node, it has to be a child of the top(page) node
see page_configuration.xsd or module-catalog\view\frontend\layout\catalog_product_view.xml
=> Fix display delivery time in product listing

Plugin/Catalog/ListProductPlugin.php
This PR fixes issue #42 
delivery block should not block output of other result html
=> fixes swatches on category view

etc/magesetup.xml
This PR fixes a part of issue #26.
The section for `at` was added in the magesetup.xml.
=> Add configuration for Austria (thanks Martin Weymayer)

view/frontend/layout/catalog_product_view.xml
=> [BUGFIX] adds missing config fix for #72

Block/Imprint/Content.php
load imprint values with store scope to allow different values for different store views
This PR fixes issue # .
...
=> [FIX] load imprint config values with scope store

etc/magesetup.xml
Bugfix for a merged where this config was removed
=> [BUGFIX] reenable at config

etc/module.xml, view/frontend/requirejs-config.js, view/frontend/web/js/configurable.js
=>  catalog_product_view_configurable: hide the tax block at tierprices if no tierprice is available

etc/magesetup.xml
- [ x ] Pull request is based against develop branch
- [ x ] README.md reflects changes (if applicable)
- [ x ] New files contain a license header
This PR fixes issue #104 .
updates tax rate from 8 to 7.7% for CH as detailed here
https://www.estv.admin.ch/estv/de/home/mehrwertsteuer/fachinformationen/steuersaetze.html
=> Updated tax rate to 7.7%

Model/Setup/SubProcessor/TaxSubProcessor.php
This PR fixes issue #127 
Change product save to updateAttribute for attribute tax_class_id
=> Fix for add tax to products with magento 2.3.x

README.md, composer.json
=> [TASK] Update dependency and readme

etc/webapi_rest/di.xml
Fix: product details were not shown on payment/review step in checkout
- [x ] Pull request is based against develop branch
- [x ] README.md reflects changes (if applicable)
- [x ] New files contain a license header
This PR fixes issue #130  .
...
=> Fix for issue #130

view/frontend/templates/imprint/email_footer.phtml
This PR fixes issue #147.
Use correct translation method.
=> Fix translation method, fixes #147

.all-contributorsrc, README.md
See result at https://github.com/kkrieger85/firegento-magesetup2
=> Update Readme, add contributors

README.md
=> Fix heading, add travis image

etc/magesetup.xml
=> Configure kg as weight unit during setup, fixes #31

view/frontend/layout/catalog_delivery_info.xml, view/frontend/layout/catalog_product_view.xml
=> Use delivery time label from attribute config

.travis.yml, Test/script/travis_install_magento.sh, Test/script/travis_script.sh, install-config-mysql.php, phpunit.integration.xml.dist
- [ X] Pull request is based against develop branch
- [ X] README.md reflects changes (if applicable)
- [ X] New files contain a license header
This PR fixes issue #166
add integration test to travis ci
=> add integration test to travis ci

composer.json
=> Remove PHP 7.1 support

Test/Integration/Observer/AddProductAttributeVisibleCheckoutObserverTest.php, Test/script/travis_before_install.sh, install-config-mysql.php
=> Add integration test for visible in checkout property

CHANGELOG.md
=> Add v0.4.0 changes
